name: Create Pull Request

on:
  workflow_dispatch: # dispatch イベントに反応する
    inputs:
      target_branch:
        description: 'Target branch for the pull request'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request
        run: |
          gh pr create --base staging --head main --title "リリース"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
