name: 'Dispatch'
on:
  workflow_dispatch:
    sample:
      description: 'This is sample input'
      required: true
      type: string
    branches: [ master ]
jobs:
  deploy:
    name: "Dispatch"
    runs-on: ubuntu-latest

    steps:
      - run: echo "ブランチが選択されました (${{ github.ref_name }})"
      - run: echo "sample text が入力されました (${{ inputs.sample }})"
