name: 'Dispatch'
on:
  workflow_dispatch:
    inputs:
      sample:
        description: 'This is sample input'
        required: true
        type: string
jobs:
  deploy:
    name: "Dispatch"
    runs-on: ubuntu-latest

    steps:
      - run: echo "sample text が入力されました (${{ inputs.sample }})"