name: Slash Command
on:
  issue_comment:
    types: [created]
jobs:
  slashCommand:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command
        uses: xt0rted/slash-command-action@v1
        with:
          commands: deploy
          reaction: "true"
          reaction-type: "eyes"
