name: Use another repo

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  useAnotherRepo:
    name: "Use another repo"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout another repo
        uses: actions/checkout@v4
        with:
          repository: oku3san/terraform-sandbox-for-work
          path: terraform-sandbox-for-work
          ssh-key: ${{ secrets.PRIVATE_REPO_SSH_KEY }}

      - name: Check
        run: ls -la terraform-sandbox-for-work
